apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
  namespace: weather-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
      - name: weather
        image: {{ .Values.image }}
        ports:
        - containerPort: 5000
        env:
        - name: OPENWEATHERMAP_API_KEY
          value: {{ .Values.openweather_key }}
        - name: FF_KEY
          value: {{ .Values.ff_key }}
