apiVersion: v1
kind: Service
metadata:
  name: weather-service
  namespace: weather-app
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30015  
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: your-app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer:
    ingress:
    - hostname: localhost
